#!/bin/bash

PANEL_FIFO=/tmp/panel-fifo
PANEL_HEIGHT=26
PANEL_FONT_FAMILY="CamingoCode:size=9"
ICON_FONT="FontAwesome:size=11"
ICON_FONT2="-*-icomoon free-*-*-*-*-*-*-*-*-*-*-*-*"

if [ $(pgrep -cx panel) -gt 1 ] ; then
        printf "%s\n" "The panel is already running." >&2
        exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc control --subscribe > "$PANEL_FIFO" &

#applauncher
echo -e 'L\uf00a' > $PANEL_FIFO &

#clock
while true; do
              echo -e 'C\ue94f' $(date +'%I:%M %p')
            sleep 5
done > "$PANEL_FIFO" &

#date
while true; do
              echo -e 'D\ue953' $(date +'%a, %d %b %Y')
            sleep 5
done > "$PANEL_FIFO" &

#power button
echo -e 'P\ue9b6' > $PANEL_FIFO &

#sleep button
echo -e 'E\uf186' > $PANEL_FIFO &

#screenlock
echo -e 'K\ue98f' > $PANEL_FIFO &

. panel_colors

cat "$PANEL_FIFO" | ~/.config/lemonbar/panel_bar | lemonbar -g x$PANEL_HEIGHT -f "$PANEL_FONT_FAMILY" -f "$ICON_FONT" -f "$ICON_FONT2" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" -u 2 | bash &

wait

