#! /bin/sh

bspc config border_width        1
bspc config window_gap        	20
bspc config top_padding         20

bspc config split_ratio         0.50

bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d $(echo -e '\uea81') $(echo -e '\ueae6') $(echo -e '\ue907') $(echo -e '\uea97') $(echo -e '\ue956') $(echo -e '\ue91f') $(echo -e '\ue910')

# Rules
bspc rule -a gimp floating=on
bspc rule -a steam floating=on
bspc rule -a firefox fullscreen=on
bspc rule -a xfce4-appfinder floating=on


## Autostart
